spring.application.name=sindhudurg
spring.data.redis.host=localhost
spring.data.redis.port=6379

# === Database Settings ===
spring.datasource.url=jdbc:postgresql://ramchandrapant-db:5432/transactions_db
spring.datasource.username=transactions_admin
spring.datasource.password=transactions_secret

# === JPA / Hibernate Settings ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
management.endpoints.web.base-path=/actuator
management.metrics.web.server.auto-time-requests=true
management.metrics.web.server.request-mapping.enabled=true

management.metrics.enable.redis=true


