spring.application.name=sindhudurg
spring.data.redis.host=localhost
spring.data.redis.port=6379

# === Database Settings ===
spring.datasource.url=jdbc:postgresql://ramchandrapant-db:5432/transactions_db
spring.datasource.username=transactions_admin
spring.datasource.password=transactions_secret

# === JPA / Hibernate Settings ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
